name: Merge

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set tag
        id: set-tag
        run: echo "tag=$(date +%Y%m%d).${{ github.run_number }}" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-tag.outputs.tag }}
          make_latest: true
          token: ${{ secrets.RELEASE_TOKEN }}
          generate_release_notes: true
